name: Generate Snake Animation

on:
  schedule:
    - cron: "0 1 * * *"  # Runs every day at 1 AM UTC
  workflow_dispatch:

jobs:
  generate-snake-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Gangatharangurusamy  # Replace with your GitHub username
          svg_out_path: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
